// One-off: removes data generated by automated testing this session, while
// keeping the real product data. Always run with --dry-run first.
//
//   npx tsx scripts/cleanup-test-fixtures.ts --dry-run
//   npx tsx scripts/cleanup-test-fixtures.ts
//
// Kept, deliberately: the 229 curated colleges, admin@campuslink.dev,
// officer@campuslink.dev (the seed demo officer), real-looking personal
// email accounts, the 3 original seed jobs/companies (ABC Technologies,
// XYZ Analytics, CloudNova), the "123456" / Graduate Software Engineer job,
// and the "USBM" college (not a timestamped test artifact).
//
// Removed: users whose email matches a test-fixture pattern (and everything
// that cascades from them: student/recruiter/staff profile, applications,
// offers, submissions, notes, etc.), the 4 timestamped test colleges, the
// explicitly-named test jobs, and the one orphaned test company they'd
// otherwise leave behind.
import { prisma } from "../src/config/prisma";

const dryRun = process.argv.includes("--dry-run");

// Matches: student1790...@test.com, officer.iitb.<ts>@test.com, anything
// @demo.test or @funnel.test, cv.tester..., resync..., p1student...,
// sqlretest... -- i.e. every timestamped/pattern-generated test account,
// while leaving real personal Gmail-style addresses untouched.
const TEST_EMAIL_PATTERN = /@(test\.com|demo\.test|funnel\.test)$/i;

const TEST_JOB_TITLE_PATTERNS = [/^Tx Check /, /^IITB Only Analyst /, /^Assignment Test Role /];

const TEST_COLLEGE_NAME_PATTERN = /^Test Institute of Engineering \d+$/;

const TEST_COMPANY_NAMES = ["Other Corp Funnel Test"];

async function main() {
  const testUsers = await prisma.user.findMany({
    where: { email: { not: undefined } },
    select: { id: true, email: true, fullName: true, role: true },
  }).then((rows) => rows.filter((u) => TEST_EMAIL_PATTERN.test(u.email)));

  const testColleges = await prisma.college.findMany({
    where: { verified: false },
    select: { id: true, name: true },
  }).then((rows) => rows.filter((c) => TEST_COLLEGE_NAME_PATTERN.test(c.name)));

  const testJobs = await prisma.job.findMany({
    select: { id: true, title: true, company: { select: { name: true } } },
  }).then((rows) => rows.filter((j) => TEST_JOB_TITLE_PATTERNS.some((p) => p.test(j.title))));

  const testCompanies = await prisma.company.findMany({
    where: { name: { in: TEST_COMPANY_NAMES } },
    select: { id: true, name: true },
  });

  // Safety checks: nothing kept should depend on what we're about to remove.
  const testUserIds = new Set(testUsers.map((u) => u.id));
  const testCollegeIds = new Set(testColleges.map((c) => c.id));
  const testJobIds = new Set(testJobs.map((j) => j.id));

  const staffOnTestColleges = await prisma.collegeStaff.findMany({
    where: { collegeId: { in: [...testCollegeIds] } },
    select: { userId: true },
  });
  const staffNotInTestUsers = staffOnTestColleges.filter((s) => !testUserIds.has(s.userId));

  const studentsOnTestColleges = await prisma.student.findMany({
    where: { collegeId: { in: [...testCollegeIds] } },
    select: { userId: true },
  });
  const studentsNotInTestUsers = studentsOnTestColleges.filter((s) => !testUserIds.has(s.userId));

  const drivesOnTestJobs = await prisma.drive.findMany({ where: { jobId: { in: [...testJobIds] } }, select: { id: true } });

  console.log(`${dryRun ? "[DRY RUN] " : ""}Test users to delete: ${testUsers.length}`);
  testUsers.forEach((u) => console.log(`  ${u.role.padEnd(17)} ${u.email}  (${u.fullName})`));

  console.log(`\nTest colleges to delete: ${testColleges.length}`);
  testColleges.forEach((c) => console.log(`  ${c.name}`));

  console.log(`\nTest jobs to delete: ${testJobs.length}`);
  testJobs.forEach((j) => console.log(`  ${j.title}  (${j.company.name})`));

  console.log(`\nOrphaned test companies to delete: ${testCompanies.length}`);
  testCompanies.forEach((c) => console.log(`  ${c.name}`));

  if (staffNotInTestUsers.length || studentsNotInTestUsers.length) {
    console.error(
      `\nABORTING: a kept user is linked to a college marked for deletion (${staffNotInTestUsers.length} staff, ${studentsNotInTestUsers.length} students). Refusing to proceed.`
    );
    process.exit(1);
  }
  if (drivesOnTestJobs.length) {
    console.error(`\nABORTING: ${drivesOnTestJobs.length} drive(s) reference a job marked for deletion. Refusing to proceed.`);
    process.exit(1);
  }
  console.log("\nSafety checks passed: nothing kept depends on anything marked for deletion.");

  if (dryRun) {
    console.log("\nDry run only -- nothing was deleted. Re-run without --dry-run to apply.");
    return;
  }

  // Order matters: users first (cascades away their Student/Recruiter/
  // CollegeStaff and everything under those), then the now-empty test
  // colleges, then the test jobs (cascades requirements/applications/etc.),
  // then the orphaned test companies.
  const deletedUsers = await prisma.user.deleteMany({ where: { id: { in: [...testUserIds] } } });
  const deletedColleges = await prisma.college.deleteMany({ where: { id: { in: [...testCollegeIds] } } });
  const deletedJobs = await prisma.job.deleteMany({ where: { id: { in: [...testJobIds] } } });
  const deletedCompanies = await prisma.company.deleteMany({ where: { id: { in: testCompanies.map((c) => c.id) } } });

  console.log(
    `\nDeleted: ${deletedUsers.count} users, ${deletedColleges.count} colleges, ${deletedJobs.count} jobs, ${deletedCompanies.count} companies.`
  );
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
